version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV
    env_file:
      - ./docker/.env
    ports:
      - "${PORT:-80}:80"
    command: npm run dev.docker
